### ISSUE TITLE
Some links are still underlined

### ISSUE THREAD

**Issue by JDemlow** [self-taught-software-developers/Self-Taught-Software-Developers.github.io#20]
Looks like some links that had the underlined text decoration removed are now back. Perhaps some old code got pushed with a recent PR. Should get fixed again.

**Comment by cerver1** [comment]
Hey James would you be able to elaborate on this issue?

**Comment by JDemlow** [comment]
Sure! When you look at the links for calendar (in the paragraph text, not the nav link), or back to the top (at the bottom of the body), the links are once again underlined, even though I believe they had been changed in a previous PR. This PR removes the text-decoration and makes the links look cleaner and more modern

**Comment by JDemlow** [comment]
Let me know if you would like further elaboration 👍

**Comment by cerver1** [comment]
That makes sense, than you James.
