### ISSUE TITLE
ReadMe Update

### ISSUE THREAD

**Issue by cerver1** [self-taught-software-developers/Self-Taught-Software-Developers.github.io#42]
Update the screenshot section of the ST-SD site's repository ReadMe with an updated screenshot of the site.

https://github.com/self-taught-software-developers/Self-Taught-Software-Developers.github.io?tab=readme-ov-file#:~:text=have%20coming%20up.-,Screenshot,-Contributing

**Comment by msaghiri** [comment]
I sent a pull request with a new screenshot

**Comment by cerver1** [comment]
completed by @msaghiri
